{{- if .Values.ingestion.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  labels:
    app: ingestion
spec:
  replicas: {{ .Values.ingestion.replicas }}
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: {{ .Values.ingestion.image }}
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: {{ .Values.ingestion.resources.requests.cpu }}
              memory: {{ .Values.ingestion.resources.requests.memory }}
            limits:
              cpu: {{ .Values.ingestion.resources.limits.cpu }}
              memory: {{ .Values.ingestion.resources.limits.memory }}
          env:
          {{- range $key, $value := .Values.ingestion.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
{{- end }}
