{{- if .Values.ingestion.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ingestion
spec:
  selector:
    app: ingestion
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
{{- end }}
