
# Use official Bun runtime as base image
FROM oven/bun:latest

WORKDIR /app


# Copy package.json and bun.lockb for installing dependencies
COPY package.json bun.lockb ./


# Install dependencies with Bun
RUN bun install --frozen-lockfile


# Copy source files
COPY . .

# Set environment variables
ENV NODE_ENV=production

# Expose port
EXPOSE 3000

# Run the service
CMD ["bun", "src/main.ts"]
